class Solution {
        /**
             * @param {character[][]} board
                  * @return {boolean}
                       */
                           isValidSudoku(board) {
                                   const rows = new Map(); // row index -> Set of numbers
                                           const cols = new Map(); // col index -> Set of numbers
                                                   const boxes = new Map(); // box index -> Set of numbers
                                                           
                                                                   for (let r = 0; r < 9; r++) {
                                                                               for (let c = 0; c < 9; c++) {
                                                                                               const val = board[r][c];
                                                                                                               
                                                                                                                               // Khali cell ko skip karein
                                                                                                                                               if (val === '.') continue;
                                                                                                                                                               
                                                                                                                                                                               // Box index calculate karein (0-8)
                                                                                                                                                                                               // Har 3x3 box ko (r/3, c/3) se identify karte hain
                                                                                                                                                                                                               const boxIndex = Math.floor(r / 3) * 3 + Math.floor(c / 3);
                                                                                                                                                                                                                               
                                                                                                                                                                                                                                               // Sets initialize karein agar pehle se nahi hain
                                                                                                                                                                                                                                                               if (!rows.has(r)) rows.set(r, new Set());
                                                                                                                                                                                                                                                                               if (!cols.has(c)) cols.set(c, new Set());
                                                                                                                                                                                                                                                                                               if (!boxes.has(boxIndex)) boxes.set(boxIndex, new Set());
                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                               // Check karein ke number pehle se mojood hai ya nahi
                                                                                                                                                                                                                                                                                                                                               if (rows.get(r).has(val) || 
                                                                                                                                                                                                                                                                                                                                                                   cols.get(c).has(val) || 
                                                                                                                                                                                                                                                                                                                                                                                       boxes.get(boxIndex).has(val)) {
                                                                                                                                                                                                                                                                                                                                                                                                           return false;
                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                           // Number ko sets mein add karein
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           rows.get(r).add(val);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           cols.get(c).add(val);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           boxes.get(boxIndex).add(val);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
